development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: base_development
  pool:     5
  username: postgres
  password: postgres
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: base_test
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: base_production
  pool:     5
  username: postgres
  password: postgres
  template: template0
